### ISSUE TITLE
Digicam Print Channel sends you to Wii Sound Settings when SPD not installed

### ISSUE THREAD

**Issue by andritolion** [WiiLink24/WiiLink24-Patcher#19]
When the Set Personal Data channel isn't installed, the Digicam Print Channel sends you to Wii Sound Settings after erroring out. I was able to reproduce this multiple times before installing SPD. I never tested with Wii Room.

**Comment by oscie57** [comment]
that from what i recall we cant fix. since spd is an installed title and it tries to launch it (and in your case you dont have it), it must launch sound settings for you. im not too sure if thats even possible to fix, so best idea is to probably install spd to fix it as its required for a couple channels.

**Comment by SketchMaster2001** [comment]
We forced it to jump to this instead of throwing you to the update menu
